### PR TITLE
Updating build tools to include LOGO

### PR DESCRIPTION
**Pull request by favna**
Aight so I'm gonna be straight here since for some reason `make` doesn't work for me on the latest code, but I don't think that is directly related to updating buildtools. I verified the makefile is correct with your recent change concerning the banner. The only real change is that I did a fetch&pull on the buildtools submodule and pushed that along with any code changes you made since I last fetched from your repo. Lastly I removed the logo file from /resources since that is loaded from buildtools automatically now.

Anyway the error I get when building is as follows - again I don't think this is directly related to this PR but it is something to look into.:

```
source/updater.c: In function 'parseResponseData':
source/updater.c:280:70: error: 'CIA_VERSION' undeclared (first use in this function)
                                 if (strncmp(assetName->u.string.ptr, CIA_VERSION, assetName->u.string.length) == 0)
                                                                      ^~~~~~~~~~~
source/updater.c:280:70: note: each undeclared identifier is reported only once for each function it appears in
make: *** [build/3ds-arm/source/updater.o] Error 1
```

When I look in Updater.c I can confirm that CIA_VERSION is indeed never declared but only used.

Lastly, disregard that commit of january 19th "add new homebrew logo", that is essentially reverted by the commits of today (11-2)

### CODE REVIEW

**Comment by Nanquitas** [comment]
It's because I was tired of changing things manually for the FONZD & PABLOMK7 versions.

So I created a few customs rules to do it automatically.
make PABLOMK7 -> will compile the normal version with pablomk7 banner
make FONZD -> will compile the normal version with fonzd version
make PABLOMK7M3 -> for mode 3
make FONZDM3 -> for mode 3

Also, if a previous build files exists, the command must be done twice (until I find a fix), once for cleaning the repo, the second for compiling.

**Comment by Nanquitas** [comment]
I updated the makefile, now one command will work, no need to send it multiple time.
Also, make re must be launched before switching mode (normal / Mode 3).

**Comment by favna** [comment]
The logo and the banner are not the same. The logo is the short splash screen/animation you see afer launching a title. An example can be seen here: https://streamable.com/3g6p4

Feel free to do this PR manually by the following commands in a terminal/cmd window (assuming you're in project source dir) (not the entire chain is directly necessary, but the first two are for updating it)

```
cd buildtools
git pull
cd ../
git add buildtools/
git commit -m "update buildtools submodule"
git push
```

(Tbh im not sure if that git add is correct as i always use git commit -am....)

**Comment by Nanquitas** [comment]
Thanks, but I already updated buildtools on my computer from the 2.4. ;)

So the start logo is already the homebrew's one. :)

**Pull request closed without merging**
