### PR TITLE
Add 11.8 support.

### PR DESCRIPTION
**Pull request by PabloMK7**
The 11.8 update only changed Process9, so the offsets of the new firm are the same.
This pull request also fixes building with the newest ctrulib version.

### CODE REVIEW

**Comment by jvhellraiser** [comment]
can anyone compile the latest nightly with the fixes?

**Comment by PabloMK7** [comment]
https://github.com/mariohackandglitch/BootNTR/releases/tag/v2.12

**Comment by jvhellraiser** [comment]
thank you, i get error on o3ds xl when trying to boot it.
this release only works on n3ds, o3ds come with and error.

**Comment by PabloMK7** [comment]
Looks like any of the cache interface offsets of the kernel were updated, so the app is broken on O3DS, will try to fix it.

**Comment by PabloMK7** [comment]
Fixed O3DS compatibility with latest commit. Cache interface addresses were offset by 0x9C bytes.

**Comment by jvhellraiser** [comment]
can you compile it so i can try it on my O3ds?

**Comment by PabloMK7** [comment]
@jvhellraiser https://github.com/Pablomf6/BootNTR/releases/tag/v2.12

**Comment by jvhellraiser** [comment]
good it works ,awesome thanks..

**Pull request merged**
