### PR TITLE
Hacky SM patcher fix for all Luma nightlies; Fix paths in graphic elements

### PR DESCRIPTION
**Pull request by mzino**
I'm sure there's a cleaner way to write it, but it works.

Checks for all the single Luma3DS 8.x.x commits that include the new SM module and skips patching on those. I will update this list until Luma3DS 9.0 is released.

### CODE REVIEW

**Comment by mzino** [comment]
Sorry for incorporating different fixes in a single PR, forgot to change branch on my second commit...

**Comment by ghost** [comment]
I really don't think is necessary; Luma3DS nightlies are not officially supported by the Luma team, they're disabled in the latest LumaUpdate releases, the nightlies site most use is broken often, etc...

**Comment by mzino** [comment]
I know, but since I coded this temporary fix for myself I thought it could be useful, while not necessary at all. Surely it doesn't hurt ;)

**Comment by Nanquitas** [comment]
Hey :)
I thank you a lot for your contribution, but I'm not fond of the hardcoded check.
We can simply read the process and check for a pattern instead of hardcoding all Luma's commits. ;)

But, your commit that fix the images etc is really welcomed, I completely forgot about that.
If you can do a separate commit, I'll surely merge it (or maybe I can separate them myself ?). ;)

**Comment by mzino** [comment]
No problem, since this is already fixed for the upcoming official release anyway.

I will commit the other changes on a proper branch and open another PR!

**Pull request closed without merging**
